# -*- coding: utf-8 -*-
"""UTSMP_RioRafliAdinanta_2702305714_inference1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8YTZKdOKaD2uqGn15JlP2VfqFdqQaxZ
"""

import streamlit as st
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib

@st.cache_resource
def load_model():
    with open("best_model_compressed.pkl", "rb") as f:
        model = joblib.load("best_model_compressed.pkl")
    return model

@st.cache_resource
def load_preprocessors():
    with open("encoders.pkl", "rb") as f:
        label_encoders = pickle.load(f)
    with open("scaler.pkl", "rb") as f:
        scaler = pickle.load(f)
    return label_encoders, scaler

model = load_model()
label_encoders, scaler = load_preprocessors()

def preprocess_input(input_df):
    df = input_df.copy()
    for col in df.select_dtypes(include=['object']).columns:
        if col in label_encoders:
            df[col] = label_encoders[col].transform(df[col])
    df_scaled = scaler.transform(df)
    return df_scaled

def main():
    st.title("Hotel Booking Prediction")

    uploaded_file = st.file_uploader("Upload data for prediction", type=["csv"])
    if uploaded_file is not None:
        input_df = pd.read_csv(uploaded_file)
        st.write("### Input Data Preview", input_df.head())

        if st.button("Predict"):
            try:
                processed_input = preprocess_input(input_df)
                prediction = model.predict(processed_input)
                input_df["Prediction"] = prediction
                st.write("### Predictions", input_df)
            except Exception as e:
                st.error(f"Prediction failed: {e}")

if __name__ == "__main__":
    main()